### ISSUE TITLE
login code not working

### ISSUE THREAD

**Issue by rupalitanna0** [rupalitanna0/myforum#1]

**Comment by DBrodsky90** [comment]
If you are logging in you should be using a POST, not a GET. You are currently using a GET and you are getting queries (?username=rr&password=2015&submit=submit).

**Comment by DBrodsky90** [comment]
Also you're not really giving enough information for me to help you out.

**Comment by DBrodsky90** [comment]
Your login form and your signup form goes to the same route? Also your syntax is wrong in the forms.

<form action="/users" name="_method" value="POST" style="clear: left; text-align: center;">

why are you doing name="_method" on a post?


it should just be ...

<form action="" method="POST">

**Comment by rupalitanna0** [comment]
it is post when i m logging in
app.post('/login', function(req, res) {
    	bcrypt.hash(req.body.password, 10, function(err, hash) {
        	var userObj = {
            	username: req.body.name,
            	password: hash
        	};
        	req.session.name = req.body.name;
        	db.create('users', userObj, function(data) {
            	res.redirect('/');
        	})
    	});
	});
and
